version: "3.8"

services:
  grafana:
    user: "1000"
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    env_file:
      - .env.secret
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.rileymathews.com`)
      - traefik.http.routers.grafana.tls.certresolver=le

  prometheus:
    user: "1000"
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - ./prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys/:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:r0
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    volumes:
      - ./etc/loki:/etc/loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
      - ./etc/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
