version: "3.8"

volumes:
  grafana-data:
  prometheus-data:

services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env.secret
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.home.rileymathews.com`)
      - traefik.http.routers.grafana.tls.certresolver=le

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys/:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:r0
    devices:
      - /dev/kmsg
    privileged: true
    restart: always
